<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="11.3.12" />
    <PackageVersion Include="Avalonia.Controls.ColorPicker" Version="11.3.12" />
    <PackageVersion Include="Avalonia.Desktop" Version="11.3.12" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.3.12" />
    <PackageVersion Include="Markdown.Avalonia" Version="11.0.2" />
    <PackageVersion Include="Material.Avalonia" Version="3.13.4" />
    <PackageVersion Include="Material.Avalonia.Dialogs" Version="3.13.4" />
    <PackageVersion Include="Material.Icons" Version="3.0.0-preview7" />
    <PackageVersion Include="Material.Icons.Avalonia" Version="3.0.0-preview7" />
  </ItemGroup>
</Project>
