<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj_run\**</DefaultItemExcludes>
    <ApplicationIcon>../Skua.Shared.Avalonia/Assets/SkuaIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Material.Avalonia" />
    <PackageReference Include="Material.Avalonia.Dialogs" />
    <PackageReference Include="Material.Icons.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Skua.Core\Skua.Core.csproj" />
    <ProjectReference Include="..\Skua.Core.Interfaces\Skua.Core.Interfaces.csproj" />
    <ProjectReference Include="..\Skua.Core.Models\Skua.Core.Models.csproj" />
    <ProjectReference Include="..\Skua.Shared.Avalonia\Skua.Shared.Avalonia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="app.manifest">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <_DeploymentManifestIconFile Remove="Assets\SkuaIcon.ico" />
  </ItemGroup>

</Project>
